# Generated by Django 2.2.3 on 2020-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docstring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=3000)),
                ('function_name', models.CharField(max_length=200)),
                ('time_behind', models.DateTimeField(blank=True, verbose_name='Time behind')),
                ('last_doc_commit', models.URLField(blank=True, max_length=1000)),
                ('code_author', models.CharField(max_length=50)),
            ],
        ),
    ]
