# Generated by Django 2.2.3 on 2020-05-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docstring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=3000)),
                ('function_name', models.CharField(max_length=200)),
                ('time_behind', models.DurationField(blank=True)),
                ('last_doc_commit', models.URLField(blank=True, max_length=1000)),
                ('code_author', models.CharField(max_length=50)),
                ('is_stale', models.BooleanField(default=False)),
                ('is_missing', models.BooleanField(default=False)),
            ],
        ),
    ]
