# Generated by Django 2.2.3 on 2020-05-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docstring',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docstring',
            name='is_stale',
            field=models.BooleanField(default=False),
        ),
    ]
