# Generated by Django 2.2.3 on 2020-05-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstring',
            name='time_behind',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
