# Generated by Django 2.2.3 on 2020-05-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0002_auto_20200508_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstring',
            name='code_author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='docstring',
            name='last_doc_commit',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
