# Generated by Django 2.2.3 on 2020-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0002_auto_20200507_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstring',
            name='time_behind',
            field=models.DurationField(blank=True),
        ),
    ]
