# Generated by Django 2.2.3 on 2020-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0003_auto_20200511_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='docstring',
            name='repo_name',
            field=models.CharField(default='maniac-bot-test', max_length=50),
            preserve_default=False,
        ),
    ]
