# Generated by Django 2.2.3 on 2020-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0004_docstring_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='docstring',
            name='blob_url',
            field=models.URLField(default='github.com', max_length=1000),
            preserve_default=False,
        ),
    ]
