# Generated by Django 2.2.3 on 2020-05-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniac', '0005_docstring_blob_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=50)),
                ('random_hash', models.CharField(max_length=200)),
            ],
        ),
    ]
